### ISSUE TITLE
"any borrowed form" documentation is incorrect

### ISSUE THREAD

**Issue by lonnen** [lonnen/mset#15]
In several places the lib used to match `map` and `sets` [api]((https://github.com/rust-lang/rust/blob/master/src/libstd/collections/hash/map.rs#L683)) of:

        K: Borrow<Q>,
        Q: Hash + Eq,

When I normalized K -> T throughout the API, I also removed this pattern but left the documentation. Either correct the docs or restore the functionality.

h/t @luser

**Comment by lonnen** [comment]
fixed in e0ab433b57ea7e3638b2658fba06dbd78e172e42, kinda.

I removed the docs instead of re-implementing the `Borrow<Q>` pattern. Unclear what I'm losing by not having that. If you find this issue later looking for the functionality, please file a new issue.

**Comment by luser** [comment]
I have no strong opinion here and I'm not using your crate but the reason for this is so you can store an owned value (like `String`) but use a borrowed form for lookups (like `&str`). If you want to store owned values without this you wind up having to use owned values for lookups as well. This may not be a problem with your usage in practice, but it's something to think about when designing generic collection types of course.

The `HashSet` example in the rust docs shows this:
https://doc.rust-lang.org/std/collections/struct.HashSet.html#examples

**Comment by lonnen** [comment]
Of course! I'm realizing that these were the first methods I put in the collection and they are, charitably, inconsistent. It's worth revisiting them now. I stole function signatures without thinking deeply about how they differ. I'll file some other issue to chase that down. I can already see a few places where it's obvious to me that I was just hacking until the compiler stopped yelling at me and the tests seemed to pass.
